FROM node:alpine As development

WORKDIR /home/app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build calculator

RUN rm -rf node_modules

RUN npm install --only=production



FROM node:alpine as production

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /home/app


COPY --from=development /home/app/dist/apps/calculator/main.js ./
COPY --from=development /home/app/node_modules ./